##### **Make sure to be in the conda environment**

In [1]:
import sys
print(sys.executable)

D:\Anaconda\envs\steam_games_analysis\python.exe

#### 1. Data Cleaning
##### **Objective:** Load, explore and clean the datasets from Steam games and reviews 
##### to create a clean dataset and begin the exploratory analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None) #To see all the columns for a better EDA

In [3]:
games = pd.read_csv('../data/raw/games.csv')
reviews = pd.read_csv('../data/raw/dataset.csv', nrows=500000) #Limit the rows so it doesnt take forever to read

print(f'Games: {games.shape}')
print(f'Reviews: {reviews.shape}')

Games: (122611, 39)
Reviews: (500000, 5)

#### **Explore both datasets**

##### **Explore the games dataset**

In [4]:
games.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,NaN,0,252,3,NaN,0,231,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,NaN,0,21,3,NaN,0,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com,True,False,False,0,NaN,0,0,0,NaN,19,0,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [5]:
games.info()

<class 'pandas.DataFrame'>
Index: 122611 entries, 2539430 to 4141790
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       122610 non-null  str
 1   Name                        122611 non-null  str
 2   Release date                122611 non-null  str
 3   Estimated owners            122611 non-null  int64
 4   Peak CCU                    122611 non-null  int64
 5   Required age                122611 non-null  float64
 6   Price                       122611 non-null  int64
 7   DiscountDLC count           122611 non-null  int64
 8   About the game              114162 non-null  str
 9   Supported languages         122611 non-null  str
 10  Full audio languages        122611 non-null  str
 11  Reviews                     12070 non-null   str
 12  Header image                122530 non-null  str
 13  Website                     49676 non-null   str
 14  Support url                 54142 non-null   str
 15  Support email               100348 non-null  str
 16  Windows                     122611 non-null  bool
 17  Mac                         122611 non-null  bool
 18  Linux                       122611 non-null  bool
 19  Metacritic score            122611 non-null  int64
 20  Metacritic url              4256 non-null    str
 21  User score                  122611 non-null  int64
 22  Positive                    122611 non-null  int64
 23  Negative                    122611 non-null  int64
 24  Score rank                  40 non-null      float64
 25  Achievements                122611 non-null  int64
 26  Recommendations             122611 non-null  int64
 27  Notes                       22458 non-null   str
 28  Average playtime forever    122611 non-null  int64
 29  Average playtime two weeks  122611 non-null  int64
 30  Median playtime forever     122611 non-null  int64
 31  Median playtime two weeks   122611 non-null  int64
 32  Developers                  114174 non-null  str
 33  Publishers                  113702 non-null  str
 34  Categories                  113658 non-null  str
 35  Genres                      114198 non-null  str
 36  Tags                        83346 non-null   str
 37  Screenshots                 116593 non-null  str
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), str(19)
memory usage: 35.0 MB

In [6]:
games.describe()

,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,Metacritic score,User score,Positive,Negative,Score rank,Achievements,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Movies
count,1.226110e+05,122611.000000,122611.000000,122611.000000,122611.000000,122611.000000,122611.000000,1.226110e+05,1.226110e+05,40.000000,122611.000000,1.226110e+05,1.226110e+05,122611.000000,1.226110e+05,122611.000000,0.0
mean,5.459332e+01,0.167611,4.765091,18.353663,0.545856,2.564941,0.024549,1.044986e+03,1.691974e+02,99.175000,18.087015,9.618250e+02,2.080232e+02,13.789268,1.735705e+02,14.722170,NaN
std,3.729452e+03,1.653591,12.531030,28.858970,14.516026,13.660559,1.394901,2.809173e+04,5.374645e+03,0.675107,141.493879,2.187880e+04,1.121768e+04,270.378053,1.120254e+04,294.509615,NaN
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,98.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
25%,0.000000e+00,0.000000,0.550000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,99.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
50%,0.000000e+00,0.000000,2.240000,0.000000,0.000000,0.000000,0.000000,5.000000e+00,1.000000e+00,99.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
75%,0.000000e+00,0.000000,5.240000,40.000000,0.000000,0.000000,0.000000,3.700000e+01,1.000000e+01,100.000000,19.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
max,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,97.000000,100.000000,7.642084e+06,1.173003e+06,100.000000,9821.000000,4.830455e+06,3.429544e+06,20088.000000,3.429544e+06,20088.000000,NaN

In [7]:
print('Nulls per column in games:')
print(games.isnull().sum())

Nulls per column in games:
AppID                              1
Name                               0
Release date                       0
Estimated owners                   0
Peak CCU                           0
Required age                       0
Price                              0
DiscountDLC count                  0
About the game                  8449
Supported languages                0
Full audio languages               0
Reviews                       110541
Header image                      81
Website                        72935
Support url                    68469
Support email                  22263
Windows                            0
Mac                                0
Linux                              0
Metacritic score                   0
Metacritic url                118355
User score                         0
Positive                           0
Negative                           0
Score rank                    122571
Achievements                       0
Recommendations                    0
Notes                         100153
Average playtime forever           0
Average playtime two weeks         0
Median playtime forever            0
Median playtime two weeks          0
Developers                      8437
Publishers                      8909
Categories                      8953
Genres                          8413
Tags                           39265
Screenshots                     6018
Movies                        122611
dtype: int64

##### **Explore the reviews dataset**

In [8]:
reviews.head()

,app_id,app_name,review_text,review_score,review_votes
0,10,Counter-Strike,Ruined my life.,1,0
1,10,Counter-Strike,This will be more of a ''my experience with th...,1,1
2,10,Counter-Strike,This game saved my virginity.,1,0
3,10,Counter-Strike,• Do you like original games? • Do you like ga...,1,0
4,10,Counter-Strike,"Easy to learn, hard to master.",1,1

In [9]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   app_id        500000 non-null  int64
 1   app_name      485494 non-null  str
 2   review_text   499072 non-null  str
 3   review_score  500000 non-null  int64
 4   review_votes  500000 non-null  int64
dtypes: int64(3), str(2)
memory usage: 19.1 MB

In [10]:
reviews.describe()

              app_id   review_score   review_votes
count  500000.000000  500000.000000  500000.000000
mean    84887.385878       0.732724       0.100158
std     65907.007716       0.680527       0.300211
min        10.000000      -1.000000       0.000000
25%     13230.000000       1.000000       0.000000
50%    105600.000000       1.000000       0.000000
75%    110800.000000       1.000000       0.000000
max    202130.000000       1.000000       1.000000

In [11]:
print('Nulls per column in reviews:')
print(reviews.isnull().sum())

Nulls per column in reviews:
app_id              0
app_name        14506
review_text       928
review_score        0
review_votes        0
dtype: int64

In [14]:
reviews['app_id'].nunique()

332

#### **Time to clean the datasets**
- **Remove nulls from critical columns**
- **Change data types if necessary**
- **Rename columns if it has ambigous name**

#### **Starting with the games dataset**

In [23]:
games_clean = games.copy()

In [24]:
drop_cols = [
    # >95% nulls
    'Movies', 'Score rank', 'Reviews', 'Notes',
    # URLs don't really care
    'Header image', 'Screenshots', 'Metacritic url',
    # Contact Info
    'Website', 'Support url', 'Support email',
    # Too much text, not planning to use it 
    'About the game', 'Full audio languages',
]
games_clean.drop(columns=drop_cols, inplace=True)
print(f"Clean columns: {games_clean.shape[1]}")

Clean columns: 27